[project]
name = "python-backend-playground"
version = "0.1.0"
description = "Python backend playground"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.121.3",
    "pyright>=1.1.407",
    "pytest>=9.0.1",
    "pytest-cov>=7.0.0",
    "ruff>=0.14.6",
]


[tool.pytest.ini_options]
addopts = "--import-mode=importlib" # 
pythonpath = "." # srcディレクトリは、srcパスを含める必要がある
testpaths = ["tests"]

[tool.ruff]
# RuffがチェックするPythonのバージョン
target-version = "py312"
# Set the maximum line length to 79.
line-length = 79
# チェック対象外とするフォルダやファイル
exclude = [
    ".git",
    "__pycache__",
    "venv",
    "docs",
]

[tool.ruff.lint]
ignore = [
    "E501",  # 行の長さ(line-length)のチェックを無効化 (フォーマッターに任せるため)
]

[tool.ruff.format]
# フォーマッターの設定（通常はデフォルトでOK）
# docstring-code-line-length = 88

[tool.pyright]
include = ["src"]  # チェック対象ディレクトリ
exclude = [
    "**/node_modules",
    "**/__pycache__",
    "**/tests",  # 最初はテストは除外してもOK
]

# 基本的な型チェックレベル
typeCheckingMode = "basic"  # "off", "basic", "standard", "strict"

# Python バージョン
pythonVersion = "3.12"
pythonPlatform = "Linux"
