[project]
name = "python-backend-playground"
version = "0.1.0"
description = "Python backend playground"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.121.3",
    "pyright>=1.1.407",
    "pytest>=9.0.1",
    "pytest-cov>=7.0.0",
    "ruff>=0.14.6",
]


[tool.pytest.ini_options]
addopts = "--import-mode=importlib" # 
pythonpath = "." # srcディレクトリは、srcパスを含める必要がある
testpaths = ["tests"]

